# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
MANDRILL_USERNAME: Your_Username
MANDRILL_APIKEY: Your_API_Key
DOMAIN_NAME: example.com
OMNIAUTH_PROVIDER_KEY: Your_Provider_Key
OMNIAUTH_PROVIDER_SECRET: Your_Provider_Secret
AWS_ACCESS_KEY_ID: Your_S3_Key
AWS_SECRET_ACCESS_KEY: Your_S3_Secret
PHAXIO_API_KEY: Your_Phaxio_Key
PHAXIO_API_SECRET: Your_Phaxio_Secret
