# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc9e40918e6ad46b883c40f57ea83c33978ef63a92fc1461ce9575321166eb07e1b55b443d12fbe6ad42d260877070af4e89045c6512fcdbb2c97c5b9d75f3e9

test:
  secret_key_base: fee3ead1937980295c479db9c73e539a019c90a849fca5fd9f69beb49e6a7f307833a969e7e46152befbc3ac9a687b045236c1311b2903ea82bdbc4f28982172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
